
name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'main.py'
          add-data: "."
          icon: "favicon.ico"
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Bilibili_Live_Stream-windows'
          options: --onefile, --name "Bilibili Live Stream", --console, 
